assignment/urls.py
from django.urls import path
from .views import add_assignment_view
from .views import assignment_view
from .views import assignment_delete_view
from .views import assignment_file_view,solution_create_view,see_student_solution
from django.conf import settings
from django.conf.urls.static import static

app_name= "assignment"

urlpatterns = [
    path('<str:slug>', assignment_view, name = 'detail'),   
    path('<str:slug>/files', assignment_file_view, name = 'assignment_file_view'),  
    path('<str:slug>/solution-submit', solution_create_view, name = 'solution_create_view'),  
    path('add/', add_assignment_view, name = 'create'),
    path('delete/<str:slug>', assignment_delete_view, name = 'delete'),
    path('<str:slug_of_assignment>/solution/<str:slug>', see_student_solution, name = 'see_student_solution'),  
]

customuser/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.auth import authenticate, login,logout

from .views import homepageview
from .views import contact_us
from .views import login_view
from .views import signup_view
from .views import logout_view
from .views import delete_user
from .views import permission_denied_view
from .views import activate,forgetpassword,changepassword,developers_page

app_name="customuser"

urlpatterns = [
    path('', homepageview, name= 'homepage'),
    path('404/', permission_denied_view, name = 'permission_denied'),
    path('login/', login_view, name = 'login'),
    path('logout/', logout_view, name = 'logout'),
    path('signup/', signup_view, name = 'signup'),
    path('contact/', contact_us, name = 'contact'),
    path('delete/', delete_user, name = 'delete'),
    path('forgetpassword/', forgetpassword, name = 'forgetpassword'),
    path('activate/<str:uidb64>/<str:token>/',
        activate, name='activate'),
    path('changepassword/<str:uidb64>/<str:token>/',
        changepassword, name='changepassword'),
    path('developerspage/', developers_page, name = 'developers_page'),

]

student/urls.py
from django.urls import path
from django.contrib.auth import authenticate, login,logout
from .views import join_class_view, StudentRegistration, HomePageViewStudent,student_edit_view,classroom_detail_view,classroom_exit_view
from django.conf.urls import url
from django.urls import include


app_name="student"

urlpatterns = [
    path('',HomePageViewStudent, name= 'homepage'),
    path('join-class/', join_class_view, name='join_class' ),
    path('edit/', student_edit_view, name='student_edit_view' ),
    path('registration/', StudentRegistration, name = 'registration'),
    path('classroom/<str:slug>/', classroom_detail_view, name='classroom_detail'),
    path('classroom/<str:slug>/exit', classroom_exit_view, name='classroom_exit_view'),
    path('classroom/<str:slug_of_class>/assignment/', include('assignment.urls')),
]

teacher/urls.py
from django.urls import path
from django.urls import include
from django.contrib.auth import authenticate, login,logout
from django.conf.urls import url
from .views import home_page_view
from .views import classroom_create_view
from .views import classroom_detail_view
from .views import teacher_edit_view
from .views import classroom_delete_view
from .views import classroom_edit_view
from .views import get_student_list

app_name="teacher"

urlpatterns = [
    path('', home_page_view, name='homepage'),
    path('edit/profile/',teacher_edit_view,name = 'teachers_edit' ),
    path('classroom/add/', classroom_create_view, name='create_classroom'),
    path('classroom/<str:slug>/', classroom_detail_view, name='classroom_detail'),
    path('classroom/<str:slug>/delete/', classroom_delete_view, name='classroom_delete'),
    path('classroom/<str:slug>/edit/', classroom_edit_view, name='classroom_edit'),
    path('classroom/<str:slug>/studentlist/', get_student_list, name='get_student_list'),
    path('classroom/<str:slug_of_class>/assignment/', include('assignment.urls')),
]

user/urls.py
from django.urls import path
from django.contrib.auth import authenticate, login,logout
from . import views
from django.conf.urls import url


app_name="user"

urlpatterns = [
    path('', views.HomePageView.as_view(), name= 'home_user'),
    path('delete/',views.delete_user, name = 'delete_user'),
    path('signup/',views.register_user_student, name = 'signup'),
    path('login/', views.login_user, name = 'login'),
    path('logout/', views.logout_view, name = 'logout'),
  

]

assignment/models.py
import os

from django.db import models
from teacher.models import TeachersClassRoom
from datetime import datetime
from django.urls import reverse

from .utils import unique_slug_generator

class Assignment(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)
    instructions = models.CharField(max_length=150, blank=True)
    due_date =  models.DateTimeField( blank=True, null = True)
    pub_date = models.DateTimeField(auto_now_add=True, null=True)
    classroom = models.ForeignKey(
        TeachersClassRoom, on_delete=models.CASCADE)
    
    def save(self, *args, **kwargs):
        self.slug = unique_slug_generator(self)
        super().save(*args, **kwargs)

    def get_files(self):
        files = AssignmentsFile.objects.filter(assignment=self)
        return files
    
    def __str__(self):
        return self.title



class AssignmentsFile(models.Model):
    file = models.FileField(upload_to='assignment/files/')
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.file)
    
    def filename(self):
        return os.path.basename(self.file.name)

assignment/forms.py
from django import forms
from .models import Assignment, AssignmentsFile
from datetime import date


class AssignmentCreateForm(forms.Form):
    class Meta:
        model = Assignment
        fields = ['title', 'instructions', 'due_date', 'assign_file', ]

    title = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'Title','class': 'border w-100 p-2 bg-white text-capitalize'}))
    instructions = forms.CharField(required=False, widget=forms.Textarea(
        attrs={'placeholder': 'Instructions if any','class':'border p-3 w-100'}))
    assign_file = forms.FileField(
        widget=forms.ClearableFileInput(attrs={'multiple': True,'class': '' ,'onchange' :'myFunction()'}))
    due_date = forms.DateTimeField(
        input_formats=['%m/%d/%Y %I:%M %p'],
        widget=forms.DateTimeInput(attrs={
            'class': ' datetimepicker-input bg-white form-control',
            'data-target': '#datetimepicker1',

            'placeholder': 'Enter Submission Date',
        })
    )

assignment/views.py
import os

from django.views.generic.edit import FormView
from django.views.generic import DetailView, ListView
from django.shortcuts import render
from django.utils.crypto import get_random_string
from django.urls import reverse
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.http import Http404
from django.shortcuts import redirect
from django.core.exceptions import ObjectDoesNotExist
from django.core.files import File
from django.contrib import messages
from django.conf import settings
from django.contrib.auth.decorators import user_passes_test
from django.utils import timezone

from teacher.models import Teacher
from teacher.models import TeachersClassRoom
from student.forms import SolutionCreateForm
from student.models import Solution
from student.models import Student, Solution, SolutionFile
from .forms import AssignmentCreateForm
from .models import AssignmentsFile
from .models import Assignment



def user_is_teacher_check(user):
    if user.is_authenticated:
        teacher = Teacher.objects.filter(user=user)
        if teacher.count() > 0:
            return True
    return False

def user_is_student_check(user):
    if user_is_teacher_check(user):
        return False
    return True

@user_passes_test(user_is_teacher_check, login_url='customuser:permission_denied')
def add_assignment_view(request, slug_of_class):
    try:
        classroom = TeachersClassRoom.objects.get(slug=slug_of_class)
        if not classroom.belongs_to_teacher(request.user):
            return render(request, '404.html')
    except ObjectDoesNotExist:
        return render(request, '404.html')
    if request.method == 'POST':
        form = AssignmentCreateForm(request.POST, request.FILES)
        files = request.FILES.getlist('assign_file')
        if form.is_valid():
            assign = Assignment(
                title=form.cleaned_data['title'],
                instructions=form.cleaned_data['instructions'],
                classroom=classroom,
                due_date=form.cleaned_data['due_date']
            )
            assign.save()
            for f in files:
                assignment_file = AssignmentsFile(file=f, assignment=assign)
                assignment_file.save()
            return HttpResponseRedirect(reverse_lazy('teacher:classroom_detail', args=(slug_of_class,)))
    else:
        form = AssignmentCreateForm()
    return render(request, 'assignment_create.html', {'form': form, 'classroom': classroom})


def assignment_view(request, slug, *args, **kwargs):
    assignment = Assignment.objects.filter(slug=slug).first()
    files = list(AssignmentsFile.objects.filter(assignment=assignment))
    if request.user.is_teacher:
        classroom = assignment.classroom
        students = classroom.student_set.all()
        students_count = students.count()
        solutions = Solution.objects.filter(assignment=assignment).order_by('submission_date')
        solutions_count = solutions.count()
        submitted_students_list = students.filter(solution__assignment = assignment).distinct()
        defaulter_list = students.exclude(pk__in=submitted_students_list)
        context = {
            'classroom':classroom,
            'assignment': assignment,
            'assignment_files': files,
            'solutions': solutions,
            'solutions_count': solutions_count,
            'students_count': students_count,
            'defaulter_list':defaulter_list,
        }
        return render(request, "assignment_view.html", context)
    else:
        context = {
            'assignment': assignment,
            'assignment_files': files,
        }
        return render(request, "student_assignment_view.html", context)


@user_passes_test(user_is_teacher_check, login_url='customuser:permission_denied')
def assignment_delete_view(request, slug, *args, **kwargs):
    try:
        assignment = Assignment.objects.get(slug=slug)
        classroom = assignment.classroom
        if not classroom.belongs_to_teacher(request.user):
            return render(request, '404.html')
    except ObjectDoesNotExist:
        return render(request, '404.html')
    assignment.delete()
    messages.success(request, "Successfully deleted")
    return HttpResponseRedirect(reverse_lazy('teacher:classroom_detail', kwargs={'slug': classroom.slug}))


def assignment_file_view(request, slug, *args, **kwargs):
    try:
        assignment = Assignment.objects.get(slug=slug)
        classroom = assignment.classroom
        if not classroom.belongs_to_teacher(request.user):
            return render(request, '404.html')
    except ObjectDoesNotExist:
        return render(request, '404.html')
    files = assignment.get_files()
    context = {
        'assignment_files': files,
    }
    return render(request, "assignment_file_view.html", context)


@user_passes_test(user_is_student_check, login_url='customuser:permission_denied')
def solution_create_view(request, slug, *args, **kwargs):
    assignment = Assignment.objects.filter(slug=slug).first()
    slug_of_class = assignment.classroom.slug 
    student = Student.objects.get(user=request.user)
    if (assignment is None or 
            not student.has_access_to_assignment(assignment)):
        return render(request, '404.html')
    if not student.has_submitted_solution(assignment):
        now = timezone.now().isoformat()
        assignment_duedate =assignment.due_date.isoformat()
        if now<assignment_duedate:
            form = SolutionCreateForm()
            if request.method == 'POST':
                form = SolutionCreateForm(request.POST, request.FILES)
                files = request.FILES.getlist('solution_file')
                if form.is_valid():
                    comment = form.cleaned_data['comment']
                    solution = Solution(
                        comment=comment, student=student, assignment=assignment)
                    solution.save()
                    for f in files:
                        solution_file = SolutionFile(
                            file=f, submission=solution)
                        solution_file.save()
                    messages.success(
                        request, "Solution to assignment is successfully submitted")
                    return redirect(reverse('student:assignment:detail',
                                kwargs={'slug_of_class':slug_of_class,'slug': slug}))
                else:
                    messages.error(request, "Please enter valid info")
            return render(request, 'student_solution_view.html',
                        {'form': form, 'assignment': assignment})
        else:
            messages.error(request,"The deadline to submit the assignment is over.")
            return redirect(reverse('student:assignment:detail',
                                kwargs={'slug_of_class':slug_of_class,'slug': slug}))
    else:
        solution = student.get_solution(assignment=assignment)
        solution_files = solution.get_files()
        return render(request, 'student_solution_view.html',
                      {'solution_files': solution_files,
                       'assignment': assignment,
                       'solution': solution})


@user_passes_test(user_is_teacher_check, login_url='customuser:permission_denied')
def see_student_solution(request, slug_of_assignment, slug, *args, **kwargs):
    sol = Solution.objects.get(slug=slug)
    assignment = Assignment.objects.get(slug=slug_of_assignment)
    solfiles = SolutionFile.objects.filter(submission=sol)
    student = sol.student
    return render(request, 'see_student_solution.html', {'solution_files': solfiles, 'assignment': assignment, 'student': student})

templates/assignment_file_view.html
<html>
    <body>
        <h1>Files:</h1>
        {% for files in assignment_files %}
        <a href="{{files.file.url}}" target="blank">{{files.filename}}</a><br>
        {% endfor %}
    </body>
</html>

templates/classroom_detail.html
{% extends "base.html" %}
{%load static%}
{% block content %}

<section class="page-title">
	<!-- Container Start -->
	<div class="container">
		<div class="row">
			<div class="col-md-9 offset-md-2 text-center">
				<!-- Title text -->
				
				<h3 style="color:  #ffc107;">{{classroom.title}} </h3>

				<br>
				
				{%if request.user.teacher %}
				
				<a class="nav-link text-white add-button" href="{% url 'teacher:assignment:create' classroom.slug  %}"><i class="fa fa-plus-circle"></i>ADD ASSIGNEMNT</a>
				{%endif%}
			</div>
		</div>
	</div>
</section>
{%if request.user.teacher %}
						
						
<section style="   padding: 15px 0;">
	<!-- Container Start -->
	<div class="container">
		<div class="row">
			<div class="col-md-9 offset-md-2 text-center">
				<!-- Title text -->
				
				<h3 style="color:  blueviolet;"><a  href="{% url 'teacher:get_student_list' classroom.slug  %}">Joined Students : {{count}}</a></h3>

				<br>
			</div>
		</div>
	</div>
</section>
{%endif%}
{% for message in messages %}
{% if message.level is DEFAULT_MESSAGE_LEVELS.ERROR %}
            <div class="alert alert-danger">
                <a class="close" href="#" data-dismiss="alert">×</a>

                {{ message }} 

            </div>
            {%else%}
            <div class="alert alert-success">
                <a class="close" href="#" data-dismiss="alert">×</a>

                {{ message }} 

            </div>
        {%endif%}
    
    {% endfor %}

<section class="user-profile section">
	<div class="container">
		<div class="row">
			<div class="col-md-10 offset-md-1 col-lg-3 offset-lg-0">
				<div class="sidebar">
					<!-- User Widget -->
					<div class="widget user-dashboard-profile">
							<!-- User Image -->
							<div class="profile-thumb">
							  <img src="{%static 'images/hands.jpg'%}" alt="" class="rounded-circle">
							</div>
							<!-- User Name -->
							<h5 class="text-center"> {{classroom.title}}</h5>
							<p>Subject :  {{classroom.subject}}</p>
							<p>Section :  {{classroom.section}}</p>
							<h2>ID :  {{classroom.class_id}}</h2><br>
							{%if request.user.teacher %}
							<a href="{% url 'teacher:assignment:create' classroom.slug  %}" class="btn btn-main-sm">Add Assignment</a>
							{%endif%}
						  </div>
					<!-- Dashboard Links -->
                    <div class="widget user-dashboard-menu">
                      <ul>  
							<li  >
						
									<a href="{% url 'customuser:homepage' %}"><i class="fa fa-folder"></i>All Classes </a></li>{%if request.user.teacher %}
									<li  >
						
										<a href="{% url 'teacher:get_student_list' classroom.slug  %}"><i class="fa fa-user"></i>Student List </a></li>
									
                    <li  >

						<a href="{% url 'teacher:classroom_edit' classroom.slug %}"><i class="fa fa-pencil"></i>Edit Class </a></li>	

                            <li><a href="" data-toggle="modal" data-target="#deleteaccount"><i class="fa fa-cog"></i>Delete
				  Class</a></li>
								{%else%}
								<li><a href="{% url 'student:classroom_exit_view' classroom.slug %}" data-toggle="modal" data-target="#deleteaccount"><i class="fa fa-sign-out"></i>Leave
									Class</a></li>
				  {%endif%}
				  
                    </ul>
          </div>
				</div>
                <div class="modal fade" id="deleteaccount" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
                  aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                      <div class="modal-header border-bottom-0">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
					  </div>
					  {% if request.user.teacher %}
                      <div class="modal-body text-center">
                        <h6 class="py-2">Are you sure you want to delete this class?</h6>
                        <p>Do you really want to delete these records? This process cannot be undone.</p>
                        <textarea name="message" id="" cols="40" rows="4" class="w-100 rounded"></textarea>
					  </div>
                      <div class="modal-footer border-top-0 mb-3 mx-5 justify-content-lg-between justify-content-center">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
                        <a href="{% url 'teacher:classroom_delete' classroom.slug %}"> <button type="button" class="btn btn-danger">Delete</button></a>
					  </div>
					  {%else%}
					  <div class="modal-body text-center">
                        <h6 class="py-2">Are you sure you want to leave this class?</h6>
                        <p>Once you leave you will not be able to get back all your records.</p>
					  </div>
                      <div class="modal-footer border-top-0 mb-3 mx-5 justify-content-lg-between justify-content-center">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
                        <a href="{% url 'student:classroom_exit_view' classroom.slug %}"> <button type="button" class="btn btn-danger">Leave</button></a>
					  </div>
					  {%endif%}
                    </div>
                  </div>
                </div>
                <!-- delete account popup modal end-->
			</div>
			<div class="col-md-10 offset-md-1 col-lg-9 offset-lg-0">
				<!-- Edit Profile Welcome Text -->
				<div class="widget welcome-message">
					<span style="font-size: 30px;">Assignments</span>
					{%if request.user.teacher %}<span style="float: right;">												
						<a data-toggle="tooltip" data-placement="top" title="Add" class="view"
						href="{% url 'teacher:assignment:create' classroom.slug  %}">
						<i class="fa fa-plus-circle" style="font-size: 40px;"></i>
					</a></span>{%endif%}
				</div>
			<div class="row">
				<div class="col-md-9">
					<div class="product-grid-list">
						<div class="row mt-30">
							{% if assignment_list %}
								{% for assignment in assignment_list %}
								<div class="col-sm-12 col-lg-4 col-md-6">
									<!-- product card -->
									<div class="product-item bg-light">
										<div class="card">
											<div class="thumb-content">
								
											</div>
								
											<div class="card-body">
												{% if request.user.teacher %}
												<a href="{%url 'teacher:assignment:detail' classroom.slug assignment.slug %}">
												{%else%}
												<a href="{%url 'student:assignment:detail' classroom.slug assignment.slug %}">
												{% endif %}
													<h4 class="card-title">{{assignment.title}}</h4>
												</a>
												<ul class="list-inline product-meta">
													<li class="list-inline-item">
														<a><i class="fa fa-calendar"></i>Due Date: : {{ assignment.due_date }}</a>
													</li>
												</ul>
												<p class="card-text">{{assignment.instructions}}</p>
								
											</div>
										</div>
									</div>
								
								
								</div>
								{%endfor%}
								{%else%}
								<h3>
									No Assignments To Show 
									{% if request.user.is_teacher %}
									<span>>>> <a href="{% url 'teacher:assignment:create' classroom.slug  %}">ADD NEW</a></span
									{% endif %}
								
								</h3>
								{%endif%}
							</div>
							</div>
							</div>



							</div> 
				</div>
			</div>
		</div>
</section>

{% endblock content %}

templates/see_student_solution.html
<html>
    <body>
        <h1>Solution of {{student}} / {{student.rollno}}:</h1>
        {% for files in solution_files %}
        <a href="{{files.file.url}}" target="blank">{{files.filename}}</a><br>
        {% endfor %}
    </body>
</html>

templates/teacher_window.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<section class="page-title">
	<!-- Container Start -->
	<div class="container">
		<div class="row">
			<div class="col-md-9 offset-md-2 text-center">
				<!-- Title text -->
				<h3>Add Class </h3>
				<h5>Click here to add classes</h5>
				<br>
				<a class="nav-link text-white add-button" href="{% url 'teacher:create_classroom' %}"><i
						class="fa fa-plus-circle"></i>ADD CLASSROOM</a>
			</div>
		</div>
	</div>
	<!-- Container End -->
</section>
{% for message in messages %}
{% if message.level is DEFAULT_MESSAGE_LEVELS.ERROR %}
<div class="alert alert-danger">
	<a class="close" href="#" data-dismiss="alert">×</a>

	{{ message }}

</div>
{%else%}
<div class="alert alert-success">
	<a class="close" href="#" data-dismiss="alert">×</a>

	{{ message }}

</div>
{%endif%}

{% endfor %}
<section class="dashboard section">
	<!-- Container Start -->
	<div class="container">
		<!-- Row Start -->
		<div class="row">
			<div class="col-md-10 offset-md-1 col-lg-4 offset-lg-0">
				<div class="sidebar">
					<!-- User Widget -->
					<div class="widget user-dashboard-profile">
						<!-- User Image -->
						<div class="profile-thumb">
							<img src="{% static 'images/pencil.png'%}" alt="" class="rounded-circle">
						</div>
						<!-- User Name -->
						<h5 class="text-center">{{teacher.name}}</h5>
						<p>{{teacher.user.email}}</p>
						<p>{{teacher.phone}}</p>
						<a href="{% url 'teacher:teachers_edit' %}" class="btn btn-main-sm">Edit Profile</a>
					</div>
					<!-- Dashboard Links -->
					<div class="widget user-dashboard-menu">
						<ul>
							<li class="active"><a href="{% url 'teacher:homepage' %}"><i class="fa fa-folder"></i>
									My Classes</a></li>
							<li><a href="{% url 'teacher:teachers_edit' %}"><i class="fa fa-user"></i>Edit Profile</a>
							</li>

							<li><a href="" data-toggle="modal" data-target="#logoutaccount"><i class="fa fa-power-off"></i>
									Logout</a></li>
							<li><a href="" data-toggle="modal" data-target="#deleteaccount"><i
										class="fa fa-cog"></i>Delete
									Account</a></li>
						</ul>
					</div>

					<!-- delete-account modal -->
					<!-- delete account popup modal start-->
					<!-- Modal -->
					<div class="modal fade" id="deleteaccount" tabindex="-1" role="dialog"
						aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
						<div class="modal-dialog modal-dialog-centered" role="document">
							<div class="modal-content">
								<div class="modal-header border-bottom-0">
									<button type="button" class="close" data-dismiss="modal" aria-label="Close">
										<span aria-hidden="true">&times;</span>
									</button>
								</div>
								<div class="modal-body text-center">
									<img src="" class="img-fluid mb-2" alt="">
									<h6 class="py-2">Are you sure you want to delete your account?</h6>
									<p>Do you really want to delete these records? This process cannot be undone.</p>
									<textarea name="message" id="" cols="40" rows="4" class="w-100 rounded"></textarea>
								</div>
								<div
									class="modal-footer border-top-0 mb-3 mx-5 justify-content-lg-between justify-content-center">
									<button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
									<a href=""> <button type="button" class="btn btn-danger">Delete</button></a>
								</div>
							</div>
						</div>
					</div>
					<!-- delete account popup modal end-->
					<div class="modal fade" id="logoutaccount" tabindex="-1" role="dialog"
						aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
						<div class="modal-dialog modal-dialog-centered" role="document">
							<div class="modal-content">
								<div class="modal-header border-bottom-0">
									<button type="button" class="close" data-dismiss="modal" aria-label="Close">
										<span aria-hidden="true">&times;</span>
									</button>
								</div>
								<div class="modal-body text-center">
									<img src="" class="img-fluid mb-2" alt="">
									<h6 class="py-2">Are you sure you want to Logout your account?</h6>
									<p>Keep smiling and selling products</p>
								</div>
								<div
									class="modal-footer border-top-0 mb-3 mx-5 justify-content-lg-between justify-content-center">
									<button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
									<a href="{% url 'customuser:logout'%}"><button type="button"
											class="btn btn-danger">Logout</button></a>
								</div>
							</div>
						</div>
					</div>
					<!-- delete-account modal -->

				</div>
			</div>
			<div class="col-md-10 offset-md-1 col-lg-8 offset-lg-0">
				<!-- Recently Favorited -->
				<div class="widget dashboard-container my-adslist">
						<span style="font-size: 20px;">My Classes</span>
						<span style="float: right;">												
							<a data-toggle="tooltip" data-placement="top" title="Add" class="view"
							href="{% url 'teacher:create_classroom' %}">
							<i class="fa fa-plus-circle" style="font-size: 30px;"></i>
						</a></span>
							<br>
							<br>
					{%if classrooms%}

					<table class="table table-responsive product-dashboard-table">
						<thead>
							<tr>
								<th>Class Title</th>
								<th>Class Section</th>
								<th class="text-center">Action</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								{% for class in classrooms %}

								<td class="product-details">
									<a href="{%url 'teacher:classroom_detail' class.slug  %}">
										<h3 class="title" style="text-transform: uppercase;">{{class.title}}</h3>
									</a>
									<h3 class="title">ID : {{class.class_id}}</h3>
									<span><strong>Subject: </strong><time>{{class.subject}}</time> </span>

									<span class="status active"><strong>Status</strong>Active</span>
								</td>
								<td class="product-category" style="text-transform: uppercase;"><span
										class="categories">{{class.section}}</span></td>
								<td class="action" data-title="Action">
									<div class="">
										<ul class="list-inline justify-content-center">
											<li class="list-inline-item">
												<a data-toggle="tooltip" data-placement="top" title="view" class="view"
													href="{%url 'teacher:classroom_detail' class.slug %}">
													<i class="fa fa-eye"></i>
												</a>
											</li>
											<li class="list-inline-item">
												<a class="edit" data-toggle="tooltip" data-placement="top" title="Edit"
													href="{% url 'teacher:classroom_edit' class.slug %}">
													<i class="fa fa-pencil"></i>
												</a>
											</li>
											<li class="list-inline-item">
												<a class="delete" data-toggle="modal" data-target="#deleteproduct"
													href="" data-placement="top" title="Delete">
													<i class="fa fa-trash"></i>
												</a>
											</li>
										</ul>
									</div>
								</td>
							</tr>
							<tr>
								<div class="modal fade" id="deleteproduct" tabindex="-1" role="dialog"
									aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
									<div class="modal-dialog modal-dialog-centered" role="document">
										<div class="modal-content">
											<div class="modal-header border-bottom-0">
												<button type="button" class="close" data-dismiss="modal"
													aria-label="Close">
													<span aria-hidden="true">&times;</span>
												</button>
											</div>
											<div class="modal-body text-center">
												<img src="" class="img-fluid mb-2" alt="">
												<h6 class="py-2">Are you sure you want to delete this Class ?</h6>
												<p>Once you delete, you will not able to get it back.</p>
											</div>
											<div
												class="modal-footer border-top-0 mb-3 mx-5 justify-content-lg-between justify-content-center">
												<button type="button" class="btn btn-primary"
													data-dismiss="modal">Cancel</button>
												<a href="{% url 'teacher:classroom_delete' class.slug %}"><button
														type="button" class="btn btn-danger">Delete</button></a>
											</div>

											{% endfor %}
											{%else%}
											<h3>No classes to show >> <a href="{% url 'teacher:create_classroom' %}">Add
													Classroom</a></h3>
											{%endif%}

						</tbody>
					</table>

				</div>

			</div>
		</div>
		<!-- Row End -->
	</div>
	<!-- Container End -->
</section>

{% endblock content %}